config/routes.rb
Bluebu::Application.routes.draw do
  get "me/index"

  root :to => "root#index"
  
  resources :articles
  resources :account, :controller => 'users' 
  resources :user_session
  
  namespace :admin do
    root :to => "root#index"
    resources :articles
    resources :categories
  end
  match '/blog', :to => 'articles#index'
  match '/code', :to => 'articles#index'
  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default '/'
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%= form_for @user, :url => account_path do |f| %>
  <%= f.label :email, "邮箱" %>
  <%= f.text_field :email %><br/>
  <%= f.label :password, "密码" %>
  <%= f.password_field :password %><br/>
  <%= f.label :password_confirmation, "密码确认" %>
  <%= f.password_field :password_confirmation %><br/>
  <%= f.submit '注册'%>
<% end %>